### ISSUE TITLE
quick checkout

### ISSUE THREAD

**Issue by tncykorkmaz** [kamilklkn/Opencart-Mesafeli-Sat-S-zle-mesi#6]
hocam merhabalar ,
ben sizin sözlşemeyi eklemeyi denedim ancak bende quickcheckout sayfası yok.
Acaba eksik bir şeyler mi var ?

**Comment by adelante25** [comment]
Merhaba, Aynı sorunu bende yaşıyorum

**Comment by kamilklkn** [comment]
Quickcheckout Opencart temalarında gelen bir eklenti. Fastor temasının son sürümünde mevcut. Sizde bu klasör yok ise eklenti yüklenmemiştir.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15580 buradaki eklenti sorununuzu çözebilir.
